Update Jenkins-pipeline-files

diff --git a/Jenkins-pipeline-files b/Jenkins-pipeline-files
--- a/Jenkins-pipeline-files
+++ b/Jenkins-pipeline-files
@@ -374,3 +374,90 @@ sudo su - jenkins
 docker ps
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 
+pipeline {
+    agent any
+
+    environment {
+        DOCKER_HUB_USER = "swaphub92"
+        IMAGE_NAME = "netflix-app"
+        IMAGE_TAG = "${BUILD_NUMBER}"
+    }
+
+    stages {
+
+        stage('Checkout Code') {
+            steps {
+                git branch: 'main',
+                    url: 'https://github.com/SwapLab92/dockerfiles.git'
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                sh '''
+                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
+                '''
+            }
+        }
+
+        stage('Verify Image') {
+            steps {
+                sh '''
+                    docker images | grep ${IMAGE_NAME}
+                '''
+            }
+        }
+
+        stage('Docker Hub Login') {
+            steps {
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'dockerhub-creds',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_TOKEN'
+                    )
+                ]) {
+                    sh '''
+                        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
+                    '''
+                }
+            }
+        }
+
+        stage('Tag Image') {
+            steps {
+                sh '''
+                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
+                    ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}
+
+                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} \
+                    ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest
+                '''
+            }
+        }
+
+        stage('Push Image') {
+            steps {
+                sh '''
+                    docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${IMAGE_TAG}
+                    docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest
+                '''
+            }
+        }
+    }
+
+    post {
+
+        success {
+            echo 'Docker image successfully pushed to Docker Hub'
+        }
+
+        failure {
+            echo 'Pipeline failed'
+        }
+
+        always {
+            sh 'docker logout || true'
+        }
+    }
+}
